name: Build Nmap on Windows with VS2019

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Set up Git repository
      run: |
        git clone https://github.com/winezer0/nmap.git nmap

    - name: Setup MSVC environment for VS2019
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build project
      working-directory: ${{ github.workspace }}/nmap/nmap/mswin32
      run: |
        Build.bat build Release
        
    - name: Archive the Release output
      uses: actions/upload-artifact@v4
      with:
        name: nmap-release-output
        path: ${{ github.workspace }}/nmap/nmap/mswin32/Release/**
