name: Build Hydra for Windows (MinGW)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. 检出源码
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. 下载并安装 MinGW-w64
      - name: Install MinGW-w64
        run: |
          # 下载 MinGW-w64 安装脚本（确保链接正确）
          curl -o mingw-get.exe https://sourceforge.net/projects/mingw-w64/files/latest/download?source=files
          
          # 创建安装目录
          mkdir mingw
          cd mingw
          
          # 将 mingw-get.exe 复制到当前目录
          move ..\mingw-get.exe .
          
          # 运行 mingw-get 安装依赖（无需解压）
          .\mingw-get install mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-pkg-config mingw-w64-x86_64-zlib mingw-w64-x86_64-openssl mingw-w64-x86_64-pcre2
          
          # 返回根目录
          cd ..

      # 3. 设置 MinGW 环境变量
      - name: Set MinGW Path
        run: |
          echo "::add-path::C:\\mingw\\mingw64\\bin"
          echo "::add-path::C:\\mingw\\msys\\1.0\\bin"

      # 4. 下载依赖库（libpcre2、libssl、libz）
      - name: Download dependencies
        run: |
          # 下载 libpcre2
          curl -o pcre2-10.42.zip https://github.com/PCRE2Project/pcre2/releases/download/release-10.42/pcre2-10.42.zip
          unzip pcre2-10.42.zip -d pcre2
          cd pcre2
          ./configure --host=x86_64-w64-mingw32 --prefix=C:/mingw/mingw64
          make -j$(nproc)
          make install
          cd ..

          # 下载 OpenSSL
          curl -o openssl-3.3.1.tar.gz https://www.openssl.org/source/openssl-3.3.1.tar.gz
          tar -xzf openssl-3.3.1.tar.gz
          cd openssl-3.3.1
          ./Configure mingw64 -prefix=C:/mingw/mingw64
          make -j$(nproc)
          make install
          cd ..

          # 下载 zlib
          curl -o zlib-1.3.tar.gz https://zlib.net/zlib-1.3.tar.gz
          tar -xzf zlib-1.3.tar.gz
          cd zlib-1.3
          ./configure --prefix=C:/mingw/mingw64
          make -j$(nproc)
          make install
          cd ..

      # 5. 编译 Hydra
      - name: Build Hydra
        run: |
          # 克隆 Hydra 源码
          git clone https://github.com/vanhauser-thc/thc-hydra.git hydra-source
          cd hydra-source

          # 配置编译参数
          ./configure --host=x86_64-w64-mingw32 --prefix=C:/mingw/mingw64 --with-ssl=C:/mingw/mingw64 --disable-x11

          # 编译 Hydra
          make -j$(nproc)

          # 创建输出目录
          mkdir -p C:/hydra-win64

          # 复制编译结果
          cp src/hydra.exe C:/hydra-win64/
          cp README.md LICENSE docs/* C:/hydra-win64/

      # 6. 打包结果
      - name: Package Hydra
        run: |
          # 打包为 ZIP
          cd C:/
          7z a hydra-win64.zip hydra-win64/

      # 7. 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hydra-win64
          path: C:/hydra-win64.zip
