name: Build Hydra for Windows (MinGW)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. 检出源码
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. 下载并安装 MSYS2（修复下载链接和验证文件）
      - name: Install MSYS2 and MinGW-w64
        run: |
          # 下载 MSYS2 安装器（使用直接链接，避免 SourceForge 重定向）
          curl -L -o msys2-installer.exe https://github.com/msys2/msys2-installer/releases/download/2025-02-21/msys2-x86_64-20250221.exe

          # 验证文件大小（确保文件未损坏）
          $fileSize = (Get-Item .\msys2-installer.exe).Length
          if ($fileSize -lt 10MB) {
            Write-Error "Downloaded file is too small (expected ~100MB, got $fileSize bytes)"
            exit 1
          }

          # 创建安装目录
          mkdir msys2
          cd msys2

          # 运行安装程序（静默安装）
          ..\msys2-installer.exe /VERYSILENT /DIR=C:\msys64

          # 更新 MSYS2 包列表
          C:\msys64\usr\bin\bash.exe -c "pacman -Syu --noconfirm"

          # 安装 MinGW-w64 工具链
          C:\msys64\usr\bin\bash.exe -c "pacman -S --noconfirm mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-pkg-config mingw-w64-ucrt-x86_64-zlib mingw-w64-ucrt-x86_64-openssl mingw-w64-ucrt-x86_64-pcre2"

          # 返回根目录
          cd ..

      # 3. 设置 MSYS2 环境变量
      - name: Set MSYS2 Path
        run: |
          echo "::add-path::C:\\msys64\\mingw64\\bin"
          echo "::add-path::C:\\msys64\\usr\\bin"

      # 4. 编译 Hydra
      - name: Build Hydra
        run: |
          # 克隆 Hydra 源码
          git clone https://github.com/vanhauser-thc/thc-hydra.git hydra-source
          cd hydra-source

          # 配置编译参数
          ./configure --host=x86_64-w64-mingw32 --prefix=C:/msys64/mingw64 --with-ssl=C:/msys64/mingw64 --disable-x11

          # 编译 Hydra
          make -j$(nproc)

          # 创建输出目录
          mkdir -p C:/hydra-win64

          # 复制编译结果
          cp src/hydra.exe C:/hydra-win64/
          cp README.md LICENSE docs/* C:/hydra-win64/

      # 5. 打包结果
      - name: Package Hydra
        run: |
          # 打包为 ZIP
          cd C:/
          7z a hydra-win64.zip hydra-win64/

      # 6. 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hydra-win64
          path: C:/hydra-win64.zip
