name: Build Hydra for Windows (Cygwin)

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. 检出源码
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. 下载并安装 Cygwin（自定义脚本）
      - name: Install Cygwin
        run: |
          # 下载 Cygwin 安装脚本
          curl -o cygwin-setup.sh https://raw.githubusercontent.com/ReanGD/setup-cygwin-action/main/entrypoint.sh
          curl -o setup-x86_64.exe https://cygwin.com/setup-x86_64.exe
          
          # 修改脚本权限并运行
          chmod +x cygwin-setup.sh
          ./cygwin-setup.sh --no-admin --quiet --root /cygwin64 --local-package-dir /tmp/cygwin-packages --packages gcc-core,make,git,libpcre-devel,libopenssl-devel,libz-devel,wget,unzip,tar

      # 3. 在 Cygwin 环境中执行编译命令
      - name: Build Hydra in Cygwin
        shell: bash
        run: |
          # 设置 Cygwin 环境变量
          export PATH="/cygwin64/bin:$PATH"
          
          # 进入工作目录
          cd /cygwin64/home/runner
          
          # 克隆 Hydra 源码
          git clone https://github.com/vanhauser-thc/thc-hydra.git hydra-source
          
          # 进入源码目录
          cd hydra-source
          
          # 配置编译参数
          ./configure --disable-x11 --with-ssl
          
          # 编译 Hydra
          make -j$(nproc)
          
          # 创建输出目录
          mkdir -p /cygwin64/home/runner/hydra-win64
          
          # 复制编译结果
          cp src/hydra.exe /cygwin64/home/runner/hydra-win64/
          cp README.md LICENSE docs/* /cygwin64/home/runner/hydra-win64/
          
          # 打包为 ZIP
          cd /cygwin64/home/runner
          zip -r hydra-win64.zip hydra-win64/

      # 4. 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hydra-win64
          path: |
            /cygwin64/home/runner/hydra-win64.zip
