name: Build Hydra for Windows (MinGW)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. 检出源码
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. 下载并安装 MSYS2（修复下载链接和验证文件）
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          
      # 4. 编译 Hydra
      - name: Build Hydra
        run: |
          # 克隆 Hydra 源码
          git clone https://github.com/vanhauser-thc/thc-hydra.git hydra-source
          cd hydra-source

          # 配置编译参数
          ./configure --host=x86_64-w64-mingw32 --prefix=C:/msys64/mingw64 --with-ssl=C:/msys64/mingw64 --disable-x11

          # 编译 Hydra
          make -j$(nproc)

          # 创建输出目录
          mkdir -p C:/hydra-win64

          # 复制编译结果
          cp src/hydra.exe C:/hydra-win64/
          cp README.md LICENSE docs/* C:/hydra-win64/

      # 5. 打包结果
      - name: Package Hydra
        run: |
          # 打包为 ZIP
          cd C:/
          7z a hydra-win64.zip hydra-win64/

      # 6. 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hydra-win64
          path: C:/hydra-win64.zip
